name: Generate Jar
on: [ push ]
jobs:
  paperclip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2.5.0
        with:
          java-version: '17'
          cache: 'gradle'
          distribution: 'temurin'
      - name: Configure Git User Details
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
      - name: 更新Jar
        uses: actions/upload-artifact@v2
        with:
          name: "ColorMirai"
          path: build/libs
